### ISSUE TITLE
Cancel non ordered role

### ISSUE THREAD

**Issue by Pajsen9263** [VermiumSifell/xyter#215]
**Describe the bug**
You can cancel other roles, I do not know if it deletes the role
**To Reproduce**
1. Go to any channel
2. Type /shop role cancel role: [any role]

**Expected behavior**
Should throw a error

**Screenshots**
![image](https://user-images.githubusercontent.com/42203569/162831250-5df1991b-b9c9-4017-b706-34158b6cb607.png)

**Comment by vermium** [comment]
Hey! Thanks for contributing! This is a serious issue, thanks for reporting it. It is fixed in #216.
