### ISSUE TITLE
Move translations into files

### ISSUE THREAD

**Issue by BolverBlitz** [VermiumSifell/xyter#250]
**Is your feature request related to a problem? Please describe.**
Yes. Once your project is bigger it will be messy

**Describe the solution you'd like**
Move stuff from `/src/locale/index.ts` to `/lang/de.json`, `/lang/en.json`, ....

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Do it.

**Comment by vermium** [comment]
Welcome, thanks for your first contribution! The reason why I have not made different files for them is that is does not work with variables or if it was plurals. I will have a solution for this soon as I will be using an localization platform instead.

**Comment by vermium** [comment]
I will deprecate language support for now, since it's a bit more advanced in my liking. Might add later or if anyone contributes an solution with a language file per language that supports namespaces too and plurals and all that stuff.
