### ISSUE TITLE
[BUG]: Credits gift value overflow when gifting more than 2147483662

### ISSUE THREAD

**Issue by nahfe** [VermiumSifell/xyter#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
Error: 
Invalid `tx.guildMember.upsert()` invocation in
/home/vermium/code/VermiumSifell/xyter/build/helpers/transferCredits.js:10:45

   7 exports.default = async (guild, from, to, amount) => {
   8     return await prisma_1.default.$transaction(async (tx) => {
   9         // 1. Decrement amount from the sender.
→ 10         const sender = await tx.guildMember.upsert(
Inconsistent column data: Conversion failed: Value -9007199254739940 does not fit in an INT column, try migrating the 'creditsEarned' column type to BIGINT
```

When gifting credits or possibly other things, if the value is too big, then it will overflow in typescript and therefore not be able to be inserted into the db. I do not believe this is because of the bigint failure that the error message is sending

### Expected Behavior

It should be restricted to the max typescript number value

### Steps To Reproduce

/credits gift user 2147483663

**Comment by vermium** [comment]
Fixed in #457
