### ISSUE TITLE
[New Command]: /math calculator

### ISSUE THREAD

**Issue by Mastergamer433** [VermiumSifell/xyter#439]
### Category

math

### Command

calculator

### What should the command do?

I would like a command for calculating basic math operations.

For example: `/math calculator 1 + 2` or `/math calculator 2 / 2`.

So it should just do basic math operations like multiplication, division, addition, subtraction, exponent, root and square root and stuff like that.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vermium** [comment]
This is moved over here: https://git.zyner.org/zyner/xyter/bot/-/issues/9
