### ISSUE TITLE
Bot can be given credits

### ISSUE THREAD

**Issue by Mastergamer433** [VermiumSifell/xyter#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When giving a bot credits (/manage credits give) it actually do give the bot the credits.

### Expected Behavior

It should cause an error cause a bot should not be able to have any credits.

### Steps To Reproduce

1. Be admin/able to run /manage commands
2. Run /manage credits give user:<bot user> amount:<an amount>

### Environment

```markdown
I do not know, the dev is hosting the bot.
```

### Anything else?

I think there should be a helper for giving a user credits that is used for this for example but also for the `/credits gift` and things like that and it should check if the user is a bot there, that way you do not need to think about checking if its a bot or user and things for giving an account credits.

**Comment by vermium** [comment]
Fixes in #465

**Comment by vermium** [comment]
Seems fixed, feel free to open this again if you find any issues related to this
