### ISSUE TITLE
Statistics system for guilds

### ISSUE THREAD

**Issue by LellisV2** [VermiumSifell/xyter#46]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
A voice channel with server stats like members and bots in the server 

**Additional context**
A good example: https://serverstatsbot.com/

**Comment by vermium** [comment]
This feature should have the ability to be toggled per guild and should be updated on schedule instead of an event. Maybe also a command viewing server counts (viewing everything the voice channels do but in text instead)

**Comment by vermium** [comment]
**Quick note**: This should be updated on a schedule every 30 minutes.

**Comment by vermium** [comment]
This is moved over here: https://git.zyner.org/zyner/xyter/bot/-/issues/10
