### ISSUE TITLE
Help wanted with fixing our cooldowns

### ISSUE THREAD

**Issue by vermium** [VermiumSifell/xyter#576]
Our cooldown system is not very reliable, we need help fixing this. The related files are [src/middlewares/cooldown/index.ts](https://github.com/ZynerOrg/xyter/blob/main/src/middlewares/cooldown/index.ts) and [src/schedules/cooldowns/index.ts](https://github.com/ZynerOrg/xyter/blob/main/src/schedules/cooldowns/index.ts)

Our problem is that people can sometimes use cooldowned two times at same time by executing them, sometimes by executing them fast and sometimes it doesnt matter. I think this is related to Async/Await code. We would be more than happy if someone could help us fix this :heart:

**Comment by BolverBlitz** [comment]
I don´t know prisma, however i know how to make it more relaiable and faster.
Instat of checking, awaiting, if check, code and then updating it you can put it into 1 query.

Do an update query for the timeout, if it returns 0 rows modifyed then he was still on timeout. If it returns 1 rows modifyed then you can execute the code.

**Comment by BolverBlitz** [comment]
Second way would be using redis, generating a "This exact thing is in processing" then run all your current code and after that release it. 
This will also work if you run your application multiple times for scaling reasons

**Comment by vermium** [comment]
> 

Sounds like less stress on the database too! Do you have an example of how such a query could look? I don't think it's a good idea to save rows for each user and so on forever, so I think you mean the timeout should be removed if 0 rows modified?

**Comment by vermium** [comment]
> Second way would be using redis, generating a "This exact thing is in processing" then run all your current code and after that release it. This will also work if you run your application multiple times for scaling reasons

Do you think Redis is a better solution for this? If so I will implement it!

**Comment by BolverBlitz** [comment]
> Do you have an example of how such a query could look?

No. As i said i do not have any experience with prisma.

> I don't think it's a good idea to save rows for each user and so on forever, so I think you mean the timeout should be removed if 0 rows modified?

I would either create a table with userid and timestamp when the last timeout was or add a row with timeout to an already existing table that stores user data.

So, for example if the timeout is 10min you can do that:
Table rows for "client_timeouts": 
discordUserId bigint
lastTimeout timestamp
```SQL
UPDATE client_timeouts SET lastTimeout = now() 
WHERE discordUserId = 'Discord User ID' AND last_timeout < now()::timestamp - INTERVAL '10 min'
```
This will only modify the row, if the timeout is older than 10 minutes, so it will only execute your code if the last timeout was 10 min or more ago

> Do you think Redis is a better solution for this?

Not if you do plan to run it multiple times in a cluster.

**Comment by vermium** [comment]
I see! Quick note tho, Xyter has multiple different cooldowns, identified with an id. I think that by keeping all cooldowns the database will grow large, I currently have a table with https://github.com/ZynerOrg/xyter/blob/main/prisma/schema.prisma#L228-L240 Should I clear cooldowns on a cron job? And just update lastTimeout field?

**Comment by vermium** [comment]
I think I solved it in this commit, https://github.com/ZynerOrg/xyter/pull/578/commits/34bb82922092d872e9c8403d71138763c3bb4189 please give feedback if you find something :blush:

**Comment by vermium** [comment]
If anyone find cooldowns having issue again, please reopen this issue :blush:
