### ISSUE TITLE
Block nsfw memes from reddit in non nsfw channels

### ISSUE THREAD

**Issue by vermium** [VermiumSifell/xyter#577]

**Comment by Pajsen9263** [comment]
Do you mean like a /reddit command or all images using the Reddit CDN?

**Comment by vermium** [comment]
The `/fun meme` grabs it from r/memes, but we need to ensure that no NSFW pictures are posted to non-nsfw channels. :)

**Comment by vermium** [comment]
Fixed in #611

**Comment by vermium** [comment]
Will be resolved in next release: 2.0.0 #611
