### ISSUE TITLE
Add avatar module to utilities plugin

### ISSUE THREAD

**Issue by Mastergamer433** [VermiumSifell/xyter#62]
**Is your feature request related to a problem? Please describe.**
No this is just useful and for fun.

**Describe the solution you'd like**
When you type /avatar it sends an embed with the avatar and name.

**Comment by vermium** [comment]
Fun to see you contributing more than once!

I like this idea, since sometimes it's hard getting my discord avatar URL when using it on websites. Would be cool if you add /avatar guild to get the current guild icon, but don't add in support to get other guilds icons, please.

**Comment by vermium** [comment]
This should be listed into utilities (/utilities avatar)

**Comment by vermium** [comment]
This should be added in 2022.5 release

**Comment by vermium** [comment]
Fixed in #240
